---
- hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  become_method: sudo
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
  pre_tasks:
    - name: install python2 requirements
      raw: sudo apt-get update && sudo apt-get -y install python-simplejson python-apt software-properties-common
  roles:
    - base